Opgops 825
ministryofjustice/opg-docker-monitoring pull request #45
Opened 2016-12-09 12:12 UTC by brettminnie

Added dockbeat container to monitor docker info and push this to es

2016-12-28 14:24 UTC, tim-mcarthur-moj requested changes

2016-12-28 14:24 UTC, tim-mcarthur-moj commented on Makefile
> +ifeq ($(tagrepo),yes)
The makefile doesn't have the workaround for semvertag needing an initial tag and also does the tag after the build rather than after the push.

2016-12-28 14:24 UTC, tim-mcarthur-moj commented on dockbeat-client/Dockerfile
> +RUN cd /tmp && \
we have an image with golang which can be used as the base for this image

2016-12-28 14:24 UTC, tim-mcarthur-moj commented on dockbeat-client/Dockerfile
> +    rm -rf PyYAML-${PYYAML_VERSION}*
is there a reason not to use pip to install pyaml

2016-12-28 14:24 UTC, tim-mcarthur-moj commented on env
> +BEATS_DOCKBEAT_MONITORING_HOST=localhost:9201
does this require a different config when connecting to a cluster.

2016-12-29 16:55 UTC, brettminnie commented on dockbeat-client/Dockerfile
> +RUN cd /tmp && \
Does not compile with Golang versions < 1.7

2016-12-29 16:56 UTC, brettminnie commented on dockbeat-client/Dockerfile
> +    rm -rf PyYAML-${PYYAML_VERSION}*
was the suggested method by Dockbeats

2016-12-29 16:56 UTC, brettminnie commented on env
> +BEATS_DOCKBEAT_MONITORING_HOST=localhost:9201
Doesn't seem so, the HOST is an array of es targets

2017-01-17 11:20 UTC, tim-mcarthur-moj approved these changes

2017-01-17 11:22 UTC, merged