Opgops 1902
ministryofjustice/opg-docker-monitoring pull request #49
Opened 2017-07-27 14:12 UTC by tim-mcarthur-moj

2017-07-27 14:25 UTC, carinadigital requested changes

2017-07-27 14:25 UTC, carinadigital commented on Makefile
> -CONTAINERS = grafana graphite-statsd logstash monitoring-proxy sensu sensu-api sensu-client sensu-server uchiwa
Are we keeping logstash code, but not producing any more images?
I would have though logstash folder would be deleted too.

2017-07-27 14:25 UTC, carinadigital commented on logstash5/docker/confd/templates/default.pipeline.conf.tmpl
> +        host => 'redis'
Should redis host be a variable?

2017-07-27 14:32 UTC, tim-mcarthur-moj commented on Makefile
> -CONTAINERS = grafana graphite-statsd logstash monitoring-proxy sensu sensu-api sensu-client sensu-server uchiwa
it can be deleted once the logstash5 config is fully rolled out

2017-07-27 14:32 UTC, tim-mcarthur-moj commented on logstash5/docker/confd/templates/default.pipeline.conf.tmpl
> +        host => 'redis'
ok. it can be.

2017-07-28 08:18 UTC, carinadigital approved these changes

2017-07-28 08:21 UTC, merged